### ISSUE TITLE
train_env_model

### ISSUE THREAD

**Issue by Waiting-TT** [ShuxinLi-Info/oef#1] opened 2022-07-25 01:29 UTC
x = torch.cat((x, action), dim=1)
RuntimeError: Expected object of scalar type float but got scalar type long int for sequence element 1.

**Comment by ShuxinLi-Info** [comment] 2022-07-25 04:25
It may be caused by the different types of x and action. It can be solved by doing the below changes in train_env_model.py file. And this change has been committed. Sorry for the inconvenience. 
![image](https://user-images.githubusercontent.com/107163197/180698154-434454a6-c0e9-4a63-870c-51ab75559f41.png)

**Closed as completed** 2022-07-26 08:59 UTC
